/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/Scene/Scene_Loading.ls
 */
export class SceneLoadingBase extends Laya.Scene {
    public loadingBar!: Laya.ProgressBar;
}

